# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:haha-fast-dev}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   hikari数据源配置，
    hikari:
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1 FROM DUAL
      #连接超时时间：毫秒 默认值30秒
      connection-timeout: 30000
      #最大连接数
      maximum-pool-size: 20
      #连接最大存活时间 默认值30分钟
      max-lifetime: 1800000
      #最小空闲连接
      minimum-idle: 5
      #空闲连接超时时间，默认值600000（10分钟）
      idle-timeout: 600000



---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:haha-fast-prod}?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   hikari数据源配置，
    hikari:
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1 FROM DUAL
      #连接超时时间：毫秒 默认值30秒
      connection-timeout: 30000
      #最大连接数
      maximum-pool-size: 20
      #连接最大存活时间 默认值30分钟
      max-lifetime: 1800000
      #最小空闲连接
      minimum-idle: 5
      #空闲连接超时时间，默认值600000（10分钟）
      idle-timeout: 600000