server:
  port: 8080
  tomcat:
    accept-count: 100
    max-connections: 10000
    min-spare-threads: 10
    max-threads: 200
    max-http-form-post-size: 2MB
    uri-encoding: UTF-8

spring:
  jackson:
    time-zone: GMT+8
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  profiles:
    include: auth,mysql,redis
    active: dev